// task_container.go - generated by api:generate task

package container

import (
	"jk-api/api/controllers/v1/handlers"
	"jk-api/pkg/repository/query/sql"
	"jk-api/pkg/services/v1"
)

func InitTaskContainer() *handlers.TaskHandler {
	repo := sql.NewTaskRepository()
	service := services.NewTaskService(repo)
	return handlers.NewTaskHandler(service)
}
