// task_dto.go - generated by api:generate task

package mapper

import (
	"jk-api/api/controllers/v1/dto"
	"jk-api/internal/database/models"
)

func CreateTaskDtoToModel(dto *dto.CreateTaskDto) (*models.Task, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Task{
		Judul:      dto.Judul,
		Deskripsi:  dto.Deskripsi,
		Status:     dto.Status,	
		Prioritas:  dto.Prioritas,
		AssignedTo: dto.AssignedTo,
		ProjectID:  dto.ProjectID,
		CreatedBy:  dto.CreatedBy,
	}

	return data, nil
}

func UpdateTaskDtoToModel(dto *dto.UpdateTaskDto) (*models.Task, error) {
	if dto == nil {
		return nil, nil
	}

	data := &models.Task{}

	if dto.Judul != nil {
		data.Judul = *dto.Judul
	}
	if dto.Deskripsi != nil {
		data.Deskripsi = *dto.Deskripsi
	}
	if dto.Status != nil {
		data.Status = *dto.Status
	}
	if dto.Prioritas != nil {
		data.Prioritas = *dto.Prioritas
	}
	if dto.AssignedTo != nil {
		data.AssignedTo = *dto.AssignedTo
	}
	if dto.ProjectID != nil {
		data.ProjectID = *dto.ProjectID
	}
	if dto.CreatedBy != nil {
		data.CreatedBy = *dto.CreatedBy
	}

	return data, nil
}

func TaskModelToResponseDto(data *models.Task) (*dto.TaskResponseDto, error) {
	if data == nil {
		return nil, nil
	}

	responseDto := &dto.TaskResponseDto{
		Task: *data,
	}

	return responseDto, nil
}
