// task_routes.go - generated by api:generate task


package routes

import (
	"jk-api/api/controllers/v1"
	"jk-api/internal/container"

	"github.com/gofiber/fiber/v2"
)

func TaskRoutes(router fiber.Router, c *container.AppContainer) {
	app := router.Group("tasks")

	app.Get("/", controllers.GetTasks(c))
	app.Post("/", controllers.CreateTasks(c))
	app.Put("/:id", controllers.UpdateTasks(c))
	app.Delete("/:id", controllers.DeleteTasks(c))
}
